[2020-12-12T20:06:57.387480+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2020-12-12T20:06:57.473062+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"07891c"},"request_uri":"https://127.0.0.1:8000/_wdt/07891c","method":"GET"} []
[2020-12-12T20:06:57.557032+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "https://127.0.0.1:8000/")" at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"https://127.0.0.1:8000/\") at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2020-12-12T20:19:51.465613+01:00] console.ERROR: Error thrown while running command "'d:d:u'". Message: "Command "d:d:u" is not defined.  Did you mean one of these?     cache:pool:prune     config:dump-reference     debug:event-dispatcher     doctrine:cache:clear-query     doctrine:cache:clear-query-region     doctrine:cache:clear-result     doctrine:database:create     doctrine:database:drop     doctrine:database:import     doctrine:ensure-production-settings     doctrine:migrations:current     doctrine:migrations:dump-schema     doctrine:migrations:execute     doctrine:migrations:rollup     doctrine:migrations:status     doctrine:migrations:up-to-date     doctrine:schema:update     make:command     make:crud     make:docker:database     make:messenger-middleware     make:reset-password     make:validator     secrets:decrypt-to-local     security:encode-password     server:dump     translation:update" {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"d:d:u\" is not defined.\n\nDid you mean one of these?\n    cache:pool:prune\n    config:dump-reference\n    debug:event-dispatcher\n    doctrine:cache:clear-query\n    doctrine:cache:clear-query-region\n    doctrine:cache:clear-result\n    doctrine:database:create\n    doctrine:database:drop\n    doctrine:database:import\n    doctrine:ensure-production-settings\n    doctrine:migrations:current\n    doctrine:migrations:dump-schema\n    doctrine:migrations:execute\n    doctrine:migrations:rollup\n    doctrine:migrations:status\n    doctrine:migrations:up-to-date\n    doctrine:schema:update\n    make:command\n    make:crud\n    make:docker:database\n    make:messenger-middleware\n    make:reset-password\n    make:validator\n    secrets:decrypt-to-local\n    security:encode-password\n    server:dump\n    translation:update at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/symfony/console/Application.php:651)","command":"'d:d:u'","message":"Command \"d:d:u\" is not defined.\n\nDid you mean one of these?\n    cache:pool:prune\n    config:dump-reference\n    debug:event-dispatcher\n    doctrine:cache:clear-query\n    doctrine:cache:clear-query-region\n    doctrine:cache:clear-result\n    doctrine:database:create\n    doctrine:database:drop\n    doctrine:database:import\n    doctrine:ensure-production-settings\n    doctrine:migrations:current\n    doctrine:migrations:dump-schema\n    doctrine:migrations:execute\n    doctrine:migrations:rollup\n    doctrine:migrations:status\n    doctrine:migrations:up-to-date\n    doctrine:schema:update\n    make:command\n    make:crud\n    make:docker:database\n    make:messenger-middleware\n    make:reset-password\n    make:validator\n    secrets:decrypt-to-local\n    security:encode-password\n    server:dump\n    translation:update"} []
[2020-12-12T20:19:54.433997+01:00] console.ERROR: Error thrown while running command "'d:d:s'". Message: "Command "d:d:s" is not defined.  Did you mean one of these?     cache:pool:list     config:dump-reference     debug:event-dispatcher     doctrine:cache:clear-result     doctrine:database:create     doctrine:database:drop     doctrine:database:import     doctrine:ensure-production-settings     doctrine:migrations:dump-schema     doctrine:migrations:latest     doctrine:migrations:list     doctrine:migrations:status     doctrine:migrations:sync-metadata-storage     doctrine:migrations:version     doctrine:query:sql     make:command     make:crud     make:docker:database     make:messenger-middleware     make:reset-password     make:validator     secrets:decrypt-to-local     security:encode-password     server:dump     translation:update" {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"d:d:s\" is not defined.\n\nDid you mean one of these?\n    cache:pool:list\n    config:dump-reference\n    debug:event-dispatcher\n    doctrine:cache:clear-result\n    doctrine:database:create\n    doctrine:database:drop\n    doctrine:database:import\n    doctrine:ensure-production-settings\n    doctrine:migrations:dump-schema\n    doctrine:migrations:latest\n    doctrine:migrations:list\n    doctrine:migrations:status\n    doctrine:migrations:sync-metadata-storage\n    doctrine:migrations:version\n    doctrine:query:sql\n    make:command\n    make:crud\n    make:docker:database\n    make:messenger-middleware\n    make:reset-password\n    make:validator\n    secrets:decrypt-to-local\n    security:encode-password\n    server:dump\n    translation:update at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/symfony/console/Application.php:651)","command":"'d:d:s'","message":"Command \"d:d:s\" is not defined.\n\nDid you mean one of these?\n    cache:pool:list\n    config:dump-reference\n    debug:event-dispatcher\n    doctrine:cache:clear-result\n    doctrine:database:create\n    doctrine:database:drop\n    doctrine:database:import\n    doctrine:ensure-production-settings\n    doctrine:migrations:dump-schema\n    doctrine:migrations:latest\n    doctrine:migrations:list\n    doctrine:migrations:status\n    doctrine:migrations:sync-metadata-storage\n    doctrine:migrations:version\n    doctrine:query:sql\n    make:command\n    make:crud\n    make:docker:database\n    make:messenger-middleware\n    make:reset-password\n    make:validator\n    secrets:decrypt-to-local\n    security:encode-password\n    server:dump\n    translation:update"} []
[2020-12-12T20:19:58.723970+01:00] console.ERROR: Error thrown while running command "'d:d:c'". Message: "An exception occurred in driver: could not find driver" {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:128)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:d:c'","message":"An exception occurred in driver: could not find driver"} []
[2020-12-12T20:19:58.724617+01:00] console.DEBUG: Command "'d:d:c'" exited with code "1" {"command":"'d:d:c'","code":1} []
[2020-12-12T20:20:55.058513+01:00] console.ERROR: Error thrown while running command "'d:s:u' --f". Message: "The "--f" option does not exist." {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): The \"--f\" option does not exist. at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/symfony/console/Input/ArgvInput.php:198)","command":"'d:s:u' --f","message":"The \"--f\" option does not exist."} []
[2020-12-12T20:20:55.059439+01:00] console.DEBUG: Command "'d:s:u' --f" exited with code "1" {"command":"'d:s:u' --f","code":1} []
[2020-12-12T20:20:59.222789+01:00] console.ERROR: Error thrown while running command "'d:s:u' --force". Message: "An exception occurred in driver: could not find driver" {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:128)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:s:u' --force","message":"An exception occurred in driver: could not find driver"} []
[2020-12-12T20:20:59.223495+01:00] console.DEBUG: Command "'d:s:u' --force" exited with code "1" {"command":"'d:s:u' --force","code":1} []
[2020-12-12T20:24:20.538668+01:00] console.ERROR: Error thrown while running command "'d:s:u' --force". Message: "An exception occurred in driver: could not find driver" {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 0): An exception occurred in driver: could not find driver at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:128)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 0): could not find driver at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 0): could not find driver at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:s:u' --force","message":"An exception occurred in driver: could not find driver"} []
[2020-12-12T20:24:20.539344+01:00] console.DEBUG: Command "'d:s:u' --force" exited with code "1" {"command":"'d:s:u' --force","code":1} []
[2020-12-12T20:41:31.557214+01:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2020-12-12T20:41:31.559427+01:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2020-12-12T20:41:31.559973+01:00] doctrine.DEBUG: CREATE TABLE `user` (id INT AUTO_INCREMENT NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, birthdate DATE NOT NULL, password VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB [] []
[2020-12-16T15:03:11.117850+01:00] console.DEBUG: Command "'d:d:c'" exited with code "1" {"command":"'d:d:c'","code":1} []
[2020-12-16T15:03:22.641840+01:00] console.ERROR: Error thrown while running command "'d:s:u'". Message: "syntax error, unexpected '}', expecting ';'" {"exception":"[object] (ParseError(code: 0): syntax error, unexpected '}', expecting ';' at /home/vigni/Documents/ESGI/tests-todo-list/app/src/Entity/User.php:130)","command":"'d:s:u'","message":"syntax error, unexpected '}', expecting ';'"} []
[2020-12-16T15:03:22.642698+01:00] console.DEBUG: Command "'d:s:u'" exited with code "1" {"command":"'d:s:u'","code":1} []
[2020-12-16T15:03:22.642841+01:00] php.CRITICAL: Uncaught Error: syntax error, unexpected '}', expecting ';' {"exception":"[object] (ParseError(code: 0): syntax error, unexpected '}', expecting ';' at /home/vigni/Documents/ESGI/tests-todo-list/app/src/Entity/User.php:130)"} []
[2020-12-16T17:29:49.491767+01:00] console.ERROR: Error thrown while running command "'d:s:u'". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:s:u'","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-16T17:29:49.493484+01:00] console.DEBUG: Command "'d:s:u'" exited with code "1" {"command":"'d:s:u'","code":1} []
[2020-12-19T16:18:45.327934+01:00] console.ERROR: Error thrown while running command "'d:d:c'". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:d:c'","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T16:18:45.331076+01:00] console.DEBUG: Command "'d:d:c'" exited with code "1" {"command":"'d:d:c'","code":1} []
[2020-12-19T16:20:55.816370+01:00] console.ERROR: Error thrown while running command "'d:d:c'". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:d:c'","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T16:20:55.817787+01:00] console.DEBUG: Command "'d:d:c'" exited with code "1" {"command":"'d:d:c'","code":1} []
[2020-12-19T16:21:13.417691+01:00] console.ERROR: Error thrown while running command "'d:d:c'". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:d:c'","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T16:21:13.419018+01:00] console.DEBUG: Command "'d:d:c'" exited with code "1" {"command":"'d:d:c'","code":1} []
[2020-12-19T16:23:26.384043+01:00] console.ERROR: Error thrown while running command "'d:d:c'". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:d:c'","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T16:23:26.387742+01:00] console.DEBUG: Command "'d:d:c'" exited with code "1" {"command":"'d:d:c'","code":1} []
[2020-12-19T16:24:40.313862+01:00] php.CRITICAL: Fatal Error: Trait 'Gedmo\Timestampable\Traits\TimestampableEntity' not found {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Error: Trait 'Gedmo\\Timestampable\\Traits\\TimestampableEntity' not found at /home/vigni/Documents/ESGI/tests-todo-list/app/src/Entity/Item.php:12)"} []
[2020-12-19T16:25:19.438152+01:00] php.CRITICAL: Fatal Error: Trait 'Gedmo\Timestampable\Traits\TimestampableEntity' not found {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Error: Trait 'Gedmo\\Timestampable\\Traits\\TimestampableEntity' not found at /home/vigni/Documents/ESGI/tests-todo-list/app/src/Entity/Item.php:12)"} []
[2020-12-19T16:28:55.269015+01:00] php.CRITICAL: Fatal Error: Trait 'Gedmo\Timestampable\Traits\TimestampableEntity' not found {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Error: Trait 'Gedmo\\Timestampable\\Traits\\TimestampableEntity' not found at /home/vigni/Documents/ESGI/tests-todo-list/app/src/Entity/Item.php:12)"} []
[2020-12-19T16:30:17.025911+01:00] php.CRITICAL: Fatal Error: Trait 'Gedmo\Timestampable\Traits\TimestampableEntity' not found {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Error: Trait 'Gedmo\\Timestampable\\Traits\\TimestampableEntity' not found at /home/vigni/Documents/ESGI/tests-todo-list/app/src/Entity/Item.php:12)"} []
[2020-12-19T16:33:10.973655+01:00] php.CRITICAL: Fatal Error: Trait 'Gedmo\Timestampable\Traits\TimestampableEntity' not found {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Error: Trait 'Gedmo\\Timestampable\\Traits\\TimestampableEntity' not found at /home/vigni/Documents/ESGI/tests-todo-list/app/src/Entity/Item.php:12)"} []
[2020-12-19T16:34:22.690593+01:00] php.CRITICAL: Fatal Error: Trait 'Gedmo\Timestampable\Traits\TimestampableEntity' not found {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Error: Trait 'Gedmo\\Timestampable\\Traits\\TimestampableEntity' not found at /home/vigni/Documents/ESGI/tests-todo-list/app/src/Entity/Item.php:12)"} []
[2020-12-19T16:36:51.559463+01:00] console.ERROR: Error thrown while running command "'d:s:u' --force". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:s:u' --force","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T16:36:51.561436+01:00] console.DEBUG: Command "'d:s:u' --force" exited with code "1" {"command":"'d:s:u' --force","code":1} []
[2020-12-19T16:37:25.885702+01:00] php.DEBUG: Warning: include(/home/vigni/Documents/ESGI/tests-todo-list/app/var/cache/de_/App_KernelDevDebugContainer.php): failed to open stream: No such file or directory {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/home/vigni/Documents/ESGI/tests-todo-list/app/vendor/symfony/http-kernel/Kernel.php","line":461,"trace":[{"file":"/home/vigni/Documents/ESGI/tests-todo-list/app/vendor/symfony/http-kernel/Kernel.php","line":461,"function":"include"}],"count":1}}} []
[2020-12-19T16:37:25.887044+01:00] php.DEBUG: Warning: include(): Failed opening '/home/vigni/Documents/ESGI/tests-todo-list/app/var/cache/de_/App_KernelDevDebugContainer.php' for inclusion (include_path='.:/usr/share/php') [] []
[2020-12-19T16:37:31.293760+01:00] console.ERROR: Error thrown while running command "'d:s:u' --force". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:s:u' --force","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T16:37:31.295306+01:00] console.DEBUG: Command "'d:s:u' --force" exited with code "1" {"command":"'d:s:u' --force","code":1} []
[2020-12-19T16:38:27.066184+01:00] php.DEBUG: Warning: include(/home/vigni/Documents/ESGI/tests-todo-list/app/var/cache/de_/App_KernelDevDebugContainer.php): failed to open stream: No such file or directory {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/home/vigni/Documents/ESGI/tests-todo-list/app/vendor/symfony/http-kernel/Kernel.php","line":461,"trace":[{"file":"/home/vigni/Documents/ESGI/tests-todo-list/app/vendor/symfony/http-kernel/Kernel.php","line":461,"function":"include"}],"count":1}}} []
[2020-12-19T16:38:27.068175+01:00] php.DEBUG: Warning: include(): Failed opening '/home/vigni/Documents/ESGI/tests-todo-list/app/var/cache/de_/App_KernelDevDebugContainer.php' for inclusion (include_path='.:/usr/share/php') [] []
[2020-12-19T16:38:32.369184+01:00] console.ERROR: Error thrown while running command "'d:s:u' --force". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:s:u' --force","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T16:38:32.370606+01:00] console.DEBUG: Command "'d:s:u' --force" exited with code "1" {"command":"'d:s:u' --force","code":1} []
[2020-12-19T16:38:49.446746+01:00] console.ERROR: Error thrown while running command "'d:s:u' --force". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:s:u' --force","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T16:38:49.448196+01:00] console.DEBUG: Command "'d:s:u' --force" exited with code "1" {"command":"'d:s:u' --force","code":1} []
[2020-12-19T16:41:54.075826+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2020-12-19T16:41:54.411058+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"d37a6c"},"request_uri":"https://localhost:8000/_wdt/d37a6c","method":"GET"} []
[2020-12-19T16:41:54.663436+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "https://localhost:8000/")" at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"https://localhost:8000/\") at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2020-12-19T16:42:35.206265+01:00] console.ERROR: Error thrown while running command "'d:s:u' --force". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:s:u' --force","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T16:42:35.207704+01:00] console.DEBUG: Command "'d:s:u' --force" exited with code "1" {"command":"'d:s:u' --force","code":1} []
[2020-12-19T16:45:19.053110+01:00] console.ERROR: Error thrown while running command "'d:s:u' --force". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:s:u' --force","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T16:45:19.055564+01:00] console.DEBUG: Command "'d:s:u' --force" exited with code "1" {"command":"'d:s:u' --force","code":1} []
[2020-12-19T16:52:31.556789+01:00] console.ERROR: Error thrown while running command "'d:d:c'". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:d:c'","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T16:52:31.557844+01:00] console.DEBUG: Command "'d:d:c'" exited with code "1" {"command":"'d:d:c'","code":1} []
[2020-12-19T16:54:33.429296+01:00] console.ERROR: Error thrown while running command "'d:s:u' --force". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:s:u' --force","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T16:54:33.430783+01:00] console.DEBUG: Command "'d:s:u' --force" exited with code "1" {"command":"'d:s:u' --force","code":1} []
[2020-12-19T17:00:37.780392+01:00] console.ERROR: Error thrown while running command "'d:s:u' --force". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:s:u' --force","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T17:00:37.782014+01:00] console.DEBUG: Command "'d:s:u' --force" exited with code "1" {"command":"'d:s:u' --force","code":1} []
[2020-12-19T17:02:39.601581+01:00] console.ERROR: Error thrown while running command "'d:s:u' --force". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:s:u' --force","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory"} []
[2020-12-19T17:02:39.603334+01:00] console.DEBUG: Command "'d:s:u' --force" exited with code "1" {"command":"'d:s:u' --force","code":1} []
[2020-12-19T17:02:48.489398+01:00] console.ERROR: Error thrown while running command "'d:s:u' --force". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:s:u' --force","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory"} []
[2020-12-19T17:02:48.490953+01:00] console.DEBUG: Command "'d:s:u' --force" exited with code "1" {"command":"'d:s:u' --force","code":1} []
[2020-12-19T17:04:00.808251+01:00] console.ERROR: Error thrown while running command "'d:s:u' --force". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:s:u' --force","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T17:04:00.809747+01:00] console.DEBUG: Command "'d:s:u' --force" exited with code "1" {"command":"'d:s:u' --force","code":1} []
[2020-12-19T17:04:41.201329+01:00] console.ERROR: Error thrown while running command "'d:s:u' --force". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:s:u' --force","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T17:04:41.202799+01:00] console.DEBUG: Command "'d:s:u' --force" exited with code "1" {"command":"'d:s:u' --force","code":1} []
[2020-12-19T17:05:49.794332+01:00] console.ERROR: Error thrown while running command "'d:s:u' --force". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:s:u' --force","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T17:05:49.796845+01:00] console.DEBUG: Command "'d:s:u' --force" exited with code "1" {"command":"'d:s:u' --force","code":1} []
[2020-12-19T17:08:12.455864+01:00] console.ERROR: Error thrown while running command "'d:d:c'". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:d:c'","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T17:08:12.457018+01:00] console.DEBUG: Command "'d:d:c'" exited with code "1" {"command":"'d:d:c'","code":1} []
[2020-12-19T17:09:27.589878+01:00] console.ERROR: Error thrown while running command "'d:d:c'". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:d:c'","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory"} []
[2020-12-19T17:09:27.591257+01:00] console.DEBUG: Command "'d:d:c'" exited with code "1" {"command":"'d:d:c'","code":1} []
[2020-12-19T17:09:35.752616+01:00] console.ERROR: Error thrown while running command "'d:d:c'". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:d:c'","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T17:09:35.753796+01:00] console.DEBUG: Command "'d:d:c'" exited with code "1" {"command":"'d:d:c'","code":1} []
[2020-12-19T17:10:16.169502+01:00] console.ERROR: Error thrown while running command "'d:d:c'". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:d:c'","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T17:10:16.170744+01:00] console.DEBUG: Command "'d:d:c'" exited with code "1" {"command":"'d:d:c'","code":1} []
[2020-12-19T17:11:42.292879+01:00] console.ERROR: Error thrown while running command "'d:d:c'". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:d:c'","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T17:11:42.293875+01:00] console.DEBUG: Command "'d:d:c'" exited with code "1" {"command":"'d:d:c'","code":1} []
[2020-12-19T17:27:01.095999+01:00] console.ERROR: Error thrown while running command "'d:d:c'". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:d:c'","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T17:27:01.097138+01:00] console.DEBUG: Command "'d:d:c'" exited with code "1" {"command":"'d:d:c'","code":1} []
[2020-12-19T17:30:30.016465+01:00] console.ERROR: Error thrown while running command "'d:d:c'". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:d:c'","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory"} []
[2020-12-19T17:30:30.018652+01:00] console.DEBUG: Command "'d:d:c'" exited with code "1" {"command":"'d:d:c'","code":1} []
[2020-12-19T17:30:32.233252+01:00] console.ERROR: Error thrown while running command "'d:d:c'". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] No such file or directory at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:d:c'","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory"} []
[2020-12-19T17:30:32.235036+01:00] console.DEBUG: Command "'d:d:c'" exited with code "1" {"command":"'d:d:c'","code":1} []
[2020-12-19T17:31:20.743639+01:00] console.ERROR: Error thrown while running command "'d:d:c'". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:d:c'","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T17:31:20.745264+01:00] console.DEBUG: Command "'d:d:c'" exited with code "1" {"command":"'d:d:c'","code":1} []
[2020-12-19T17:45:46.710312+01:00] console.ERROR: Error thrown while running command "'d:d:c'". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:d:c'","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T17:45:46.711547+01:00] console.DEBUG: Command "'d:d:c'" exited with code "1" {"command":"'d:d:c'","code":1} []
[2020-12-19T17:48:36.247728+01:00] console.ERROR: Error thrown while running command "'d:d:c'". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:d:c'","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T17:48:36.248941+01:00] console.DEBUG: Command "'d:d:c'" exited with code "1" {"command":"'d:d:c'","code":1} []
[2020-12-19T20:02:51.969789+01:00] console.ERROR: Error thrown while running command "'d:d:dc'". Message: "Command "d:d:dc" is not defined.  Did you mean one of these?     config:dump-reference     debug:event-dispatcher     doctrine:database:create     doctrine:database:drop     doctrine:database:import     doctrine:ensure-production-settings     make:command     make:crud     make:docker:database     make:messenger-middleware     make:reset-password     make:validator     secrets:decrypt-to-local     security:encode-password     server:dump     translation:update" {"exception":"[object] (Symfony\\Component\\Console\\Exception\\CommandNotFoundException(code: 0): Command \"d:d:dc\" is not defined.\n\nDid you mean one of these?\n    config:dump-reference\n    debug:event-dispatcher\n    doctrine:database:create\n    doctrine:database:drop\n    doctrine:database:import\n    doctrine:ensure-production-settings\n    make:command\n    make:crud\n    make:docker:database\n    make:messenger-middleware\n    make:reset-password\n    make:validator\n    secrets:decrypt-to-local\n    security:encode-password\n    server:dump\n    translation:update at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/symfony/console/Application.php:651)","command":"'d:d:dc'","message":"Command \"d:d:dc\" is not defined.\n\nDid you mean one of these?\n    config:dump-reference\n    debug:event-dispatcher\n    doctrine:database:create\n    doctrine:database:drop\n    doctrine:database:import\n    doctrine:ensure-production-settings\n    make:command\n    make:crud\n    make:docker:database\n    make:messenger-middleware\n    make:reset-password\n    make:validator\n    secrets:decrypt-to-local\n    security:encode-password\n    server:dump\n    translation:update"} []
[2020-12-19T20:02:54.444560+01:00] console.ERROR: Error thrown while running command "'d:d:c'". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution" {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 2002): SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)\n[previous exception] [object] (PDOException(code: 0): PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution at /home/vigni/Documents/ESGI/tests-todo-list/app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)","command":"'d:d:c'","message":"An exception occurred in driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"} []
[2020-12-19T20:02:54.445526+01:00] console.DEBUG: Command "'d:d:c'" exited with code "1" {"command":"'d:d:c'","code":1} []
[2020-12-19T20:07:24.780307+01:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2020-12-19T20:07:24.783636+01:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2020-12-19T20:07:24.784133+01:00] doctrine.DEBUG: CREATE TABLE item (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, name VARCHAR(255) NOT NULL, content LONGTEXT NOT NULL, UNIQUE INDEX UNIQ_1F1B251E5E237E06 (name), INDEX IDX_1F1B251EA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB [] []
[2020-12-19T20:07:24.792927+01:00] doctrine.DEBUG: CREATE TABLE `user` (id INT AUTO_INCREMENT NOT NULL, first_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, birthdate DATE NOT NULL, password VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB [] []
[2020-12-19T20:07:24.801083+01:00] doctrine.DEBUG: ALTER TABLE item ADD CONSTRAINT FK_1F1B251EA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) [] []
[2020-12-19T20:14:06.802660+01:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2020-12-19T20:14:06.803661+01:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'todo_list_db' AND TABLE_NAME = 'item' ORDER BY ORDINAL_POSITION ASC [] []
[2020-12-19T20:14:06.804603+01:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'item' */ WHERE k.table_name = 'item' AND k.table_schema = 'todo_list_db' /*!50116 AND c.constraint_schema = 'todo_list_db' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2020-12-19T20:14:06.805141+01:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'item' AND TABLE_SCHEMA = 'todo_list_db' ORDER BY SEQ_IN_INDEX ASC [] []
[2020-12-19T20:14:06.805524+01:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'item' [] []
[2020-12-19T20:14:06.805815+01:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'todo_list_db' AND TABLE_NAME = 'user' ORDER BY ORDINAL_POSITION ASC [] []
[2020-12-19T20:14:06.806396+01:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'user' */ WHERE k.table_name = 'user' AND k.table_schema = 'todo_list_db' /*!50116 AND c.constraint_schema = 'todo_list_db' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2020-12-19T20:14:06.806840+01:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'user' AND TABLE_SCHEMA = 'todo_list_db' ORDER BY SEQ_IN_INDEX ASC [] []
[2020-12-19T20:14:06.807119+01:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'user' [] []
[2020-12-19T20:14:06.808748+01:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2020-12-19T20:14:06.809117+01:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'todo_list_db' AND TABLE_NAME = 'item' ORDER BY ORDINAL_POSITION ASC [] []
[2020-12-19T20:14:06.809568+01:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'item' */ WHERE k.table_name = 'item' AND k.table_schema = 'todo_list_db' /*!50116 AND c.constraint_schema = 'todo_list_db' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2020-12-19T20:14:06.809893+01:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'item' AND TABLE_SCHEMA = 'todo_list_db' ORDER BY SEQ_IN_INDEX ASC [] []
[2020-12-19T20:14:06.810206+01:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'item' [] []
[2020-12-19T20:14:06.810465+01:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'todo_list_db' AND TABLE_NAME = 'user' ORDER BY ORDINAL_POSITION ASC [] []
[2020-12-19T20:14:06.810881+01:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'user' */ WHERE k.table_name = 'user' AND k.table_schema = 'todo_list_db' /*!50116 AND c.constraint_schema = 'todo_list_db' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2020-12-19T20:14:06.811218+01:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'user' AND TABLE_SCHEMA = 'todo_list_db' ORDER BY SEQ_IN_INDEX ASC [] []
[2020-12-19T20:14:06.811450+01:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'user' [] []
[2020-12-19T20:14:06.811843+01:00] doctrine.DEBUG: ALTER TABLE user ADD created_at DATETIME NOT NULL, ADD updated_at DATETIME NOT NULL [] []
[2020-12-19T20:50:36.144325+01:00] php.DEBUG: Warning: include(/home/vigni/Documents/ESGI/tests-todo-list/app/var/cache/de_/App_KernelDevDebugContainer.php): failed to open stream: No such file or directory {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/home/vigni/Documents/ESGI/tests-todo-list/app/vendor/symfony/http-kernel/Kernel.php","line":461,"trace":[{"file":"/home/vigni/Documents/ESGI/tests-todo-list/app/vendor/symfony/http-kernel/Kernel.php","line":461,"function":"include"}],"count":1}}} []
[2020-12-19T20:50:36.144928+01:00] php.DEBUG: Warning: include(): Failed opening '/home/vigni/Documents/ESGI/tests-todo-list/app/var/cache/de_/App_KernelDevDebugContainer.php' for inclusion (include_path='.:/usr/share/php') [] []
[2020-12-19T21:42:07.790240+01:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2020-12-19T21:42:07.806884+01:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'todo_list_db' AND TABLE_NAME = 'item' ORDER BY ORDINAL_POSITION ASC [] []
[2020-12-19T21:42:07.822541+01:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'item' */ WHERE k.table_name = 'item' AND k.table_schema = 'todo_list_db' /*!50116 AND c.constraint_schema = 'todo_list_db' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2020-12-19T21:42:07.825578+01:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'item' AND TABLE_SCHEMA = 'todo_list_db' ORDER BY SEQ_IN_INDEX ASC [] []
[2020-12-19T21:42:07.828045+01:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'item' [] []
[2020-12-19T21:42:07.829772+01:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'todo_list_db' AND TABLE_NAME = 'user' ORDER BY ORDINAL_POSITION ASC [] []
[2020-12-19T21:42:07.831203+01:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'user' */ WHERE k.table_name = 'user' AND k.table_schema = 'todo_list_db' /*!50116 AND c.constraint_schema = 'todo_list_db' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2020-12-19T21:42:07.832191+01:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'user' AND TABLE_SCHEMA = 'todo_list_db' ORDER BY SEQ_IN_INDEX ASC [] []
[2020-12-19T21:42:07.832787+01:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'user' [] []
[2020-12-19T21:42:07.836691+01:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2020-12-19T21:42:07.837537+01:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'todo_list_db' AND TABLE_NAME = 'item' ORDER BY ORDINAL_POSITION ASC [] []
[2020-12-19T21:42:07.838404+01:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'item' */ WHERE k.table_name = 'item' AND k.table_schema = 'todo_list_db' /*!50116 AND c.constraint_schema = 'todo_list_db' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2020-12-19T21:42:07.839175+01:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'item' AND TABLE_SCHEMA = 'todo_list_db' ORDER BY SEQ_IN_INDEX ASC [] []
[2020-12-19T21:42:07.839788+01:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'item' [] []
[2020-12-19T21:42:07.840364+01:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'todo_list_db' AND TABLE_NAME = 'user' ORDER BY ORDINAL_POSITION ASC [] []
[2020-12-19T21:42:07.841189+01:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'user' */ WHERE k.table_name = 'user' AND k.table_schema = 'todo_list_db' /*!50116 AND c.constraint_schema = 'todo_list_db' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2020-12-19T21:42:07.841793+01:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'user' AND TABLE_SCHEMA = 'todo_list_db' ORDER BY SEQ_IN_INDEX ASC [] []
[2020-12-19T21:42:07.842257+01:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'user' [] []
[2020-12-19T21:42:07.842867+01:00] doctrine.DEBUG: ALTER TABLE item ADD created_at DATETIME NOT NULL, ADD updated_at DATETIME NOT NULL [] []
[2020-12-19T21:43:13.729543+01:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2020-12-19T21:43:13.731132+01:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'todo_list_db' AND TABLE_NAME = 'item' ORDER BY ORDINAL_POSITION ASC [] []
[2020-12-19T21:43:13.733007+01:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'item' */ WHERE k.table_name = 'item' AND k.table_schema = 'todo_list_db' /*!50116 AND c.constraint_schema = 'todo_list_db' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2020-12-19T21:43:13.733465+01:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'item' AND TABLE_SCHEMA = 'todo_list_db' ORDER BY SEQ_IN_INDEX ASC [] []
[2020-12-19T21:43:13.733815+01:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'item' [] []
[2020-12-19T21:43:13.734100+01:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'todo_list_db' AND TABLE_NAME = 'user' ORDER BY ORDINAL_POSITION ASC [] []
[2020-12-19T21:43:13.734681+01:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'user' */ WHERE k.table_name = 'user' AND k.table_schema = 'todo_list_db' /*!50116 AND c.constraint_schema = 'todo_list_db' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2020-12-19T21:43:13.735069+01:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'user' AND TABLE_SCHEMA = 'todo_list_db' ORDER BY SEQ_IN_INDEX ASC [] []
[2020-12-19T21:43:13.735377+01:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'user' [] []
